# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\x13\x65nterprise.fintrack\"=\n\x10\x45mbeddingRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\"S\n\x11\x45mbeddingResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x12\n\ndimensions\x18\x02 \x01(\x05\x12\x1a\n\x12processing_time_ms\x18\x03 \x01(\x03\"3\n\nRAGRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontext_chunks\x18\x02 \x03(\t\".\n\x0bRAGResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x32\xcd\x01\n\x10\x45mbeddingService\x12\x62\n\x11GenerateEmbedding\x12%.enterprise.fintrack.EmbeddingRequest\x1a&.enterprise.fintrack.EmbeddingResponse\x12U\n\x0eGenerateAnswer\x12\x1f.enterprise.fintrack.RAGRequest\x1a .enterprise.fintrack.RAGResponse0\x01\x42\x37\n\x1c\x63om.enterprise.fintrack.grpcB\x15\x45mbeddingServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.enterprise.fintrack.grpcB\025EmbeddingServiceProtoP\001'
  _globals['_EMBEDDINGREQUEST']._serialized_start=40
  _globals['_EMBEDDINGREQUEST']._serialized_end=101
  _globals['_EMBEDDINGRESPONSE']._serialized_start=103
  _globals['_EMBEDDINGRESPONSE']._serialized_end=186
  _globals['_RAGREQUEST']._serialized_start=188
  _globals['_RAGREQUEST']._serialized_end=239
  _globals['_RAGRESPONSE']._serialized_start=241
  _globals['_RAGRESPONSE']._serialized_end=287
  _globals['_EMBEDDINGSERVICE']._serialized_start=290
  _globals['_EMBEDDINGSERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
