/**
 * Fintrack GraphRAG SEC Analytics Platform - Type Definitions
 * 
 * These types mirror the backend's data structures for seamless
 * integration with the Java Netty API Gateway.
 */



/**
 * Backend semantic chunk format (schema mismatch fix)
 * Backend returns: {text, cik, score}
 * Frontend expects: {text, ticker, similarityScore}
 */
export interface BackendSemanticChunk {
  /** The actual text content */
  text: string;
  /** CIK identifier (e.g., "1467373") */
  cik: string;
  /** Similarity score from vector search */
  score: number;
  /** Optional: Section identifier */
  section?: string;
  /** Optional: Year */
  year?: number;
  /** Optional: Document type */
  document_type?: string;
}

/**
 * Backend query response format
 * Backend returns: {semantic_chunks: [...], generated_answer: string}
 */
export interface BackendQueryResponse {
  /** Array of semantic chunks with raw backend format */
  semantic_chunks: BackendSemanticChunk[];
  /** The LLM-generated answer */
  generated_answer: string;
  /** Optional: Conversation ID */
  conversation_id?: string;
  /** Optional: Metadata */
  metadata?: {
    query_time_ms?: number;
    chunks_retrieved?: number;
    model_used?: string;
    tokens_generated?: number;
  };
}



/**
 * Represents a semantic chunk retrieved from Neo4j Knowledge Graph.
 * These are the paragraph-level embeddings stored in the graph.
 */
export interface SemanticChunk {
  /** Unique identifier for the chunk (e.g., "AAPL-2023-10K-ITEM7-001") */
  id: string;
  /** The actual text content of the SEC filing paragraph */
  text: string;
  /** Source document (e.g., "10-K", "MD&A", "8-K") */
  documentType: string;
  /** Company ticker symbol */
  ticker: string;
  /** Filing year */
  year: number;
  /** Section of the filing (e.g., "Item 7 - MD&A") */
  section: string;
  /** Similarity score from vector search (0-1) */
  similarityScore: number;
  /** Vector embedding (optional, for debugging) */
  embedding?: number[];
}

/**
 * Graph node representing an entity in the Knowledge Graph.
 */
export interface GraphNode {
  /** Unique node ID */
  id: string;
  /** Node type for styling */
  type: 'company' | 'document' | 'chunk' | 'concept' | 'metric';
  /** Display label */
  label: string;
  /** Raw text content (for chunk nodes) */
  content?: string;
  /** Additional metadata */
  data?: Record<string, unknown>;
  /** Position in the graph (auto-calculated if not provided) */
  position?: { x: number; y: number };
}

/**
 * Graph edge representing relationships between nodes.
 */
export interface GraphEdge {
  /** Unique edge ID */
  id: string;
  /** Source node ID */
  source: string;
  /** Target node ID */
  target: string;
  /** Relationship type (e.g., "CONTAINS", "REFERENCES", "RELATED_TO") */
  type: string;
  /** Edge weight for visualization */
  weight?: number;
}


/**
 * Citation reference within an LLM response.
 * Maps to a specific semantic chunk.
 */
export interface Citation {
  /** Citation number displayed in UI (e.g., 1, 2, 3) */
  number: number;
  /** Reference to the semantic chunk */
  chunkId: string;
  /** Preview text for hover tooltip */
  preview: string;
  /** Full chunk data (loaded on demand) */
  chunk?: SemanticChunk;
}

/**
 * A single message in the chat history.
 */
export interface ChatMessage {
  /** Unique message ID */
  id: string;
  /** Message role */
  role: 'user' | 'assistant' | 'system';
  /** Message content (accumulated for streaming) */
  content: string;
  /** Timestamp */
  timestamp: Date;
  /** Citations referenced in this message */
  citations?: Citation[];
  /** Associated semantic chunks for graph visualization */
  semanticChunks?: SemanticChunk[];
  /** Streaming state */
  isStreaming?: boolean;
  /** Error state */
  error?: string;
}

/**
 * Stream chunk received from Java Netty backend.
 * The backend streams partial responses as they're generated by Python LLM.
 */
export interface StreamChunk {
  /** Chunk type */
  type: 'token' | 'citation' | 'chunk' | 'error' | 'complete';
  /** Token text (for type='token') */
  token?: string;
  /** Citation data (for type='citation') */
  citation?: Citation;
  /** Semantic chunk (for type='chunk') */
  semanticChunk?: SemanticChunk;
  /** Error message (for type='error') */
  error?: string;
  /** Complete flag (for type='complete') */
  complete?: boolean;
}



/**
 * Request payload to Java API Gateway.
 */
export interface QueryRequest {
  /** User's natural language query */
  query: string;
  /** Optional ticker filter */
  ticker?: string;
  /** Optional year filter */
  year?: number;
  /** Number of semantic chunks to retrieve */
  topK?: number;
  /** Conversation ID for context */
  conversationId?: string;
}

/**
 * Response structure from Java API Gateway.
 * Note: In streaming mode, this comes as SSE chunks.
 */
export interface QueryResponse {
  /** Generated answer from LLM */
  answer: string;
  /** Citations used in the answer */
  citations: Citation[];
  /** Semantic chunks retrieved from Neo4j */
  semanticChunks: SemanticChunk[];
  /** Execution metadata */
  metadata: {
    queryTimeMs: number;
    chunksRetrieved: number;
    modelUsed: string;
    tokensGenerated: number;
  };
}



/**
 * Graph visualization state.
 */
export interface GraphState {
  /** Current nodes in the graph */
  nodes: GraphNode[];
  /** Current edges in the graph */
  edges: GraphEdge[];
  /** Selected node ID */
  selectedNodeId: string | null;
  /** Expanded node IDs (showing full content) */
  expandedNodeIds: string[];
  /** Graph layout algorithm */
  layout: 'force' | 'hierarchical' | 'circular';
  /** Loading state */
  isLoading: boolean;
}

/**
 * Chat state.
 */
export interface ChatState {
  /** Message history */
  messages: ChatMessage[];
  /** Current streaming message */
  streamingMessage: ChatMessage | null;
  /** Input value */
  inputValue: string;
  /** Loading state */
  isLoading: boolean;
  /** Error state */
  error: string | null;
  /** Conversation ID */
  conversationId: string;
  /** Inference loading state (for long-running inference) */
  isInferenceLoading: boolean;
}

/**
 * Application-wide UI state.
 */
export interface UIState {
  /** Sidebar collapsed state */
  sidebarCollapsed: boolean;
  /** Active panel (for mobile) */
  activePanel: 'chat' | 'graph';
  /** Theme */
  theme: 'dark' | 'light';
  /** Panel sizes (for resizable panels) */
  panelSizes: {
    left: number;
    right: number;
  };
}

/**
 * Conversation history item for sidebar
 */
export interface ConversationHistoryItem {
  /** Conversation ID */
  id: string;
  /** Query snippet or title */
  query: string;
  /** Timestamp */
  timestamp: Date;
  /** Number of messages */
  messageCount: number;
}
